##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.7.0-B52] date: [Tue Nov 11 05:58:32 CET 2025]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = stm32f401-usb-keyboard-amiga
DEBUG ?= 0
DEBUG_USB ?= 0

# Librerie et al.
include Makefile.common

######################################
# source
######################################
# C sources
C_SOURCES = \
	src/main.c \
	src/log_task.c \
	src/delay_us.c \
	src/usb_task.c \
	src/amiga_task.c \
	src/led_manager_task.c \
	src/eeprom_task.c \
	src/freertos.c \
	src/stm32f4xx_it.c \
	src/stm32f4xx_hal_msp.c \
	src/stm32f4xx_hal_timebase_tim.c \
	src/amiga.c \
	src/system_stm32f4xx.c \
	src/sysmem.c \
	src/syscalls.c \
	src/ee.c \


C_SOURCES += \
	$(USB_HOST_C_SOURCES)


C_SOURCES += \
	$(LIBRARY_C_SOURCES)


C_SOURCES += \
	$(FREERTOS_SOURCES)


# ASM sources
ASM_SOURCES =  \
	startup_stm32f401xc.s

# ASMM sources
ASMM_SOURCES = 

# ASMMC sources
ASMMC_SOURCE = 

include Makefile.board

# AS includes
AS_INCLUDES =  \
	-Iinc \
	$(USB_HOST_C_INCLUDES) \
	$(LIBRARY_C_INCLUDES) \
	$(FREERTOS_INCLUDES) \
	

# C includes
C_INCLUDES =  \
	-Iinc \
	$(USB_HOST_C_INCLUDES) \
	$(LIBRARY_C_INCLUDES) \
	$(FREERTOS_INCLUDES) \
	


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

EASTER_EGG ?= no
AMIBERRY_EASTER_EGG ?= no

# Add EASTER_EGG=yes in the makefile command
ifeq ($(EASTER_EGG), yes)
	CFLAGS += -D__EASTER_EGG__ \

endif

# Add AMIBERRY_EASTER_EGG = yes in the makefile command
ifeq ($(AMIBERRY_EASTER_EGG), yes)
	CFLAGS += \
		-D__EASTER_EGG__ \
		-D__AMIBERRY_EASTER_EGG__ \

endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32f401xx_flash.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMMC_SOURCES:.c=.o)))
vpath %.S $(sort $(dir $(ASMMC_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
